### PR TITLE
Added User-Agent to installMod headers

### PR DESCRIPTION
**Pull request by HeyImKyu**
Github needs a User-Agent or will respond with 403
Have no chance to test on OSX unfortunately, but working on Windows

### CODE REVIEW

**Comment by HeyImKyu** [comment]
Don't merge before OSX is tested or OSX part is reverted

**Comment by HeyImKyu** [comment]
OSX Part reverted now, cause no-one was testing it, 
Can be tested and merged 
fyi @UwUDev

**Comment by UwUDev** [comment]
Looks good to me, just merge the last commits there are conflict

**Comment by HeyImKyu** [comment]
Can now be merged

**Pull request merged**
