### PR TITLE
Trying to find steam path from registry

### PR DESCRIPTION
**Pull request by HeyImKyu**
I had problems installing balamod yesterday because I dont have Steam installed in C:\\
So I tried to implement a registry lookup now.

Any comments welcome as this is my first time working with rust and I'm a bit confused :D

### CODE REVIEW

**Comment by UwUDev** [comment]
Looks good to me, i just need to test it on various VM installation to be 100% sure it works

Also, if the reg key don't exist you should even try to see if the vdf file still exist in the C drive in case of

**Comment by UwUDev** [comment]
And if you could also make the winreg lib and this part compile only on windows that would be even better c:

**Comment by HeyImKyu** [comment]
Added those two things and tested them on my own system (windows).
Cant say if the conditional compilation actually works 🤷‍♀️

**Comment by UwUDev** [comment]
If you could try to recompile it on windows

**Comment by HeyImKyu** [comment]
Oh, sorry i missed this

Yes, seems to be working on my end

**Pull request merged**
